a = (input('Digite algo: '))
print ('O tipo primitivo desse valor é  ', type(a))
print ('Só tem espaço?', a.isspace())
print ('Só tem letra maiúscula?', a.isupper())
print ('Só tem letra minúscula?', a.islower())
print ('É um número?', a.isnumeric())
print ('É alphanumérico?', a.isalnum())
print ('É alfabético?', a.isalpha())
print ('Está capitalizada?', a.istitle())