a = str(input('Qual o nome do aluno:'))
n1 = int(input('Digite a primeira nota: '))
n2 = int(input('Digite a segunda nota: '))
n3 = int(input('Digite a terceira nota: '))
n4 = int(input('Digite a quarta nota: '))
print(f'A nota média do aluno {a} é {(n1+n2+n3+n4)/4}')